from fastapi import APIRouter, Depends, HTTPException, Request, Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
import time

from app.persistence.database import get_db
from app.persistence.models.user import UserRow, WorkspaceRow, WorkspaceMembershipRow
from app.auth.schemas import SignupRequest, LoginRequest, AuthResponse, MeResponse, WorkspaceSummary
from app.auth.password import hash_password, verify_password
from app.auth.session import create_session, revoke_session
from app.auth.csrf import generate_csrf_token
from app.api.dependencies import get_current_user, csrf_protect, _extract_bearer
from app.core.config import settings

router = APIRouter(prefix="/auth", tags=["auth"])

def _set_auth_cookies(response: Response, raw_token: str, csrf_token: str) -> None:
    """Helper to consistently set session and CSRF cookies."""
    response.set_cookie(
        key="session",
        value=raw_token,
        httponly=True,
        samesite="lax",
        secure=settings.SECURE_COOKIES,
        max_age=settings.SESSION_TTL_SECONDS,
        path="/"
    )
    
    csrf_key = "__Host-csrf" if settings.SECURE_COOKIES else "csrf_token"
    response.set_cookie(
        key=csrf_key,
        value=csrf_token,
        httponly=False,  # Must be readable by frontend for double-submit
        samesite="lax",
        secure=settings.SECURE_COOKIES,
        max_age=settings.SESSION_TTL_SECONDS,
        path="/"
    )


@router.post("/signup", response_model=AuthResponse)
async def signup(request_data: SignupRequest, response: Response, request: Request, db: AsyncSession = Depends(get_db)):
    """Create a new user account, an initial workspace, and return a session token."""
    
    email = request_data.email.lower().strip()
    
    # Pre-check email to avoid messy integrity errors in logs
    stmt = select(UserRow).where(UserRow.email == email)
    existing_user = (await db.execute(stmt)).scalar_one_or_none()
    if existing_user:
        raise HTTPException(status_code=409, detail="Email already registered")

    # Hash password
    hashed_pwd = hash_password(request_data.password)
    
    # Create user
    user = UserRow(
        email=email,
        password_hash=hashed_pwd,
        display_name=request_data.display_name
    )
    db.add(user)
    
    # Create workspace
    workspace = WorkspaceRow(name=request_data.workspace_name)
    db.add(workspace)
    
    # We must flush to get IDs (they are generated by default functions in SQLAlchemy)
    await db.flush()
    
    # Create membership
    membership = WorkspaceMembershipRow(
        workspace_id=workspace.id,
        user_id=user.id,
        role="OWNER"
    )
    db.add(membership)
    
    # Create session
    raw_token = await create_session(
        user_id=user.id,
        db=db,
        user_agent=request.headers.get("user-agent"),
        ip_address=request.client.host if request.client else None
    )
    
    csrf_token = generate_csrf_token()
    
    await db.commit()
    
    _set_auth_cookies(response, raw_token, csrf_token)
    
    return AuthResponse(
        user_id=user.id,
        email=user.email,
        display_name=user.display_name,
        workspace_ids=[workspace.id]
    )

@router.post("/login", response_model=AuthResponse)
async def login(request_data: LoginRequest, response: Response, request: Request, db: AsyncSession = Depends(get_db)):
    """Verify credentials and issue a session token."""
    email = request_data.email.lower().strip()
    
    stmt = select(UserRow).where(UserRow.email == email)
    user = (await db.execute(stmt)).scalar_one_or_none()
    
    # Constant-time-ish check: always verify even if user not found (use dummy hash if needed)
    # This prevents user-enumeration via timing attacks.
    if not user:
        # Dummy verification to consume time
        verify_password(request_data.password, "$argon2id$v=19$m=65536,t=2,p=2$dummy$dummy")
        raise HTTPException(status_code=401, detail="Invalid email or password")
        
    if not verify_password(request_data.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Invalid email or password")
        
    if user.status != "ACTIVE":
        raise HTTPException(status_code=403, detail="Account is disabled")

    # Issue session
    raw_token = await create_session(
        user_id=user.id,
        db=db,
        user_agent=request.headers.get("user-agent"),
        ip_address=request.client.host if request.client else None
    )
    
    csrf_token = generate_csrf_token()
    
    await db.commit()
    
    _set_auth_cookies(response, raw_token, csrf_token)
    
    # Get user workspaces
    ws_stmt = select(WorkspaceMembershipRow.workspace_id).where(WorkspaceMembershipRow.user_id == user.id)
    ws_ids = (await db.execute(ws_stmt)).scalars().all()
    
    return AuthResponse(
        user_id=user.id,
        email=user.email,
        display_name=user.display_name,
        workspace_ids=ws_ids
    )


@router.post("/logout", dependencies=[Depends(csrf_protect)])
async def logout(request: Request, response: Response, db: AsyncSession = Depends(get_db)):
    """Revoke the current session and clear cookies."""
    bearer_token = _extract_bearer(request)
    token_to_revoke = bearer_token if bearer_token else request.cookies.get("session")
    
    if token_to_revoke:
        await revoke_session(token_to_revoke, db)
        await db.commit()
        
    response.delete_cookie(key="session", path="/", secure=settings.SECURE_COOKIES, samesite="lax")
    csrf_key = "__Host-csrf" if settings.SECURE_COOKIES else "csrf_token"
    response.delete_cookie(key=csrf_key, path="/", secure=settings.SECURE_COOKIES, samesite="lax")
    
    response.status_code = 204
    return None


@router.get("/me", response_model=MeResponse)
async def me(current_user: UserRow = Depends(get_current_user), db: AsyncSession = Depends(get_db)):
    """Return info about the currently authenticated user."""
    stmt = select(WorkspaceMembershipRow).where(WorkspaceMembershipRow.user_id == current_user.id)
    memberships = (await db.execute(stmt)).scalars().all()
    
    # To get workspace names efficiently without heavy relationship loads just for this route:
    ws_ids = [m.workspace_id for m in memberships]
    workspaces = []
    
    if ws_ids:
        ws_stmt = select(WorkspaceRow).where(WorkspaceRow.id.in_(ws_ids))
        ws_rows = (await db.execute(ws_stmt)).scalars().all()
        ws_map = {row.id: row.name for row in ws_rows}
        
        for m in memberships:
            workspaces.append(WorkspaceSummary(
                id=m.workspace_id,
                name=ws_map.get(m.workspace_id, "Unknown"),
                role=m.role
            ))
            
    return MeResponse(
        user_id=current_user.id,
        email=current_user.email,
        display_name=current_user.display_name,
        status=current_user.status,
        workspaces=workspaces
    )
