"""phase_17

Revision ID: 29e9f222144f
Revises: b52485b26ba1
Create Date: 2026-09-17 12:56:00.713829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e9f222144f'
down_revision: Union[str, Sequence[str], None] = 'b52485b26ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('canonical_source', sa.String(length=255), nullable=False),
    sa.Column('requested_revision', sa.String(length=255), nullable=False),
    sa.Column('resolved_commit', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('manifest_hash', sa.String(length=255), nullable=False),
    sa.Column('analyzer_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_snapshots_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_snapshots_resolved_commit'), ['resolved_commit'], unique=False)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('analyzer_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_analyses_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_foreign_key('fk_analyses_snapshot_id_repository_snapshots', 'repository_snapshots', ['snapshot_id'], ['snapshot_id'])
        batch_op.drop_column('repository_manifest_hash')

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_column('provider_metadata')
        batch_op.drop_column('provider_type')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repository_manifest_hash', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('fk_analyses_snapshot_id_repository_snapshots', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_analyses_snapshot_id'))
        batch_op.drop_column('error_message')
        batch_op.drop_column('analyzer_version')
        batch_op.drop_column('snapshot_id')

    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_snapshots_resolved_commit'))
        batch_op.drop_index(batch_op.f('ix_repository_snapshots_repository_id'))

    op.drop_table('repository_snapshots')
    # ### end Alembic commands ###
