"""add sessions

Revision ID: b52485b26ba1
Revises: df39e0038509
Create Date: 2026-09-17 00:35:46.829772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52485b26ba1'
down_revision: Union[str, Sequence[str], None] = 'df39e0038509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    with op.batch_alter_table('environment_fingerprints') as batch_op:
        batch_op.alter_column('os_name',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('python_version',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('tool_name',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('tool_version',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment_fingerprints') as batch_op:
        batch_op.alter_column('tool_version',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('tool_name',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('python_version',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('os_name',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
