"""phase_18c_integrations

Revision ID: c3e8837a4e67
Revises: f5a124d6c534
Create Date: 2026-09-17 17:07:22.291736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e8837a4e67'
down_revision: Union[str, Sequence[str], None] = 'f5a124d6c534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambiguity_cases',
    sa.Column('ambiguity_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('requirement_ids', sa.JSON(), nullable=False),
    sa.Column('candidate_ids', sa.JSON(), nullable=False),
    sa.Column('ambiguity_types', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('ambiguity_id')
    )
    op.create_table('change_records',
    sa.Column('change_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('base_commit', sa.String(length=255), nullable=False),
    sa.Column('target_commit', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_classification', sa.String(length=50), nullable=True),
    sa.Column('file_change_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('change_id')
    )
    with op.batch_alter_table('change_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_records_base_commit'), ['base_commit'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_records_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_records_target_commit'), ['target_commit'], unique=False)

    op.create_table('counterexamples',
    sa.Column('counterexample_id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('contract_id', sa.String(length=255), nullable=True),
    sa.Column('obligation_id', sa.String(length=255), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.String(), nullable=False),
    sa.Column('preconditions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('counterexample_id')
    )
    with op.batch_alter_table('counterexamples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterexamples_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterexamples_obligation_id'), ['obligation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterexamples_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterexamples_target_id'), ['target_id'], unique=False)

    op.create_table('drift_reports',
    sa.Column('drift_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('base_commit', sa.String(length=255), nullable=False),
    sa.Column('target_commit', sa.String(length=255), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('impacts', sa.JSON(), nullable=False),
    sa.Column('invalidations', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('drift_id')
    )
    with op.batch_alter_table('drift_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drift_reports_base_commit'), ['base_commit'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_reports_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_reports_target_commit'), ['target_commit'], unique=False)

    op.create_table('evidences',
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=True),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('observation', sa.String(), nullable=False),
    sa.Column('collected_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidences_commit_id'), ['commit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('execution_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('obligation_id', sa.String(length=255), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.Column('requested_permissions', sa.JSON(), nullable=False),
    sa.Column('granted_permissions', sa.JSON(), nullable=False),
    sa.Column('sandbox_backend', sa.String(length=50), nullable=False),
    sa.Column('command_identity', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_audits_commit_id'), ['commit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_audits_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_audits_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_audits_obligation_id'), ['obligation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_audits_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_audits_target_id'), ['target_id'], unique=False)

    op.create_table('execution_results',
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('exit_code', sa.String(length=50), nullable=True),
    sa.Column('stdout', sa.String(), nullable=True),
    sa.Column('stderr', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.String(), nullable=True),
    sa.Column('timed_out', sa.String(length=50), nullable=True),
    sa.Column('resource_limit_exceeded', sa.String(length=50), nullable=True),
    sa.Column('sandbox_backend', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('execution_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_results_commit_id'), ['commit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_results_repository_id'), ['repository_id'], unique=False)

    op.create_table('intent_candidates',
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('analysis_id', sa.String(length=255), nullable=False),
    sa.Column('original_statement', sa.String(), nullable=False),
    sa.Column('normalized_statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('human_confirmed', sa.Boolean(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    with op.batch_alter_table('intent_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intent_candidates_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('invalidation_records',
    sa.Column('invalidation_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_id', sa.String(length=255), nullable=False),
    sa.Column('previous_commit', sa.String(length=255), nullable=False),
    sa.Column('target_commit', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('related_change_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('invalidation_id')
    )
    op.create_table('obligation_verifications',
    sa.Column('obligation_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=False),
    sa.Column('contradicting_evidence', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('obligation_id')
    )
    with op.batch_alter_table('obligation_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligation_verifications_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligation_verifications_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('requirement_verifications',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('obligation_results', sa.JSON(), nullable=False),
    sa.Column('unresolved_obligations', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_verifications_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_verifications_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('semantic_conditions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semantic_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_conditions_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('semantic_contracts',
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('contract_version', sa.String(length=50), nullable=False),
    sa.Column('parent_contract_id', sa.String(length=255), nullable=True),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('candidate_id', sa.String(length=255), nullable=True),
    sa.Column('analysis_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('compilation_status', sa.String(length=50), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    with op.batch_alter_table('semantic_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_contracts_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_semantic_contracts_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_semantic_contracts_parent_contract_id'), ['parent_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_semantic_contracts_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('semantic_impacts',
    sa.Column('impact_id', sa.String(length=255), nullable=False),
    sa.Column('change_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_id', sa.String(length=255), nullable=False),
    sa.Column('affected_requirements', sa.JSON(), nullable=False),
    sa.Column('affected_contracts', sa.JSON(), nullable=False),
    sa.Column('affected_obligations', sa.JSON(), nullable=False),
    sa.Column('affected_targets', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('impact_id')
    )
    with op.batch_alter_table('semantic_impacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_impacts_change_id'), ['change_id'], unique=False)

    op.create_table('semantic_requirements',
    sa.Column('requirement_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=True),
    sa.Column('analysis_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('original_statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    with op.batch_alter_table('semantic_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_requirements_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_semantic_requirements_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('skeptic_reports',
    sa.Column('report_id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('contract_id', sa.String(length=255), nullable=True),
    sa.Column('total_generated', sa.Integer(), nullable=False),
    sa.Column('total_deduplicated', sa.Integer(), nullable=False),
    sa.Column('strategies_applied', sa.JSON(), nullable=False),
    sa.Column('counterexamples', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('skeptic_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skeptic_reports_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skeptic_reports_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('verification_reports',
    sa.Column('verification_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('requirement_results', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('verification_id')
    )
    with op.batch_alter_table('verification_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_reports_commit_id'), ['commit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_reports_repository_id'), ['repository_id'], unique=False)

    op.create_table('webhook_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('provider_repository_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_provider_repository_id'), ['provider_repository_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavior_expectations',
    sa.Column('behavior_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('is_allowed', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('expected_outcome', sa.String(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('behavior_id')
    )
    with op.batch_alter_table('behavior_expectations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavior_expectations_contract_id'), ['contract_id'], unique=False)

    op.create_table('clarification_questions',
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('ambiguity_id', sa.String(length=255), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('distinguishing_scenario_id', sa.String(length=255), nullable=True),
    sa.Column('information_gain', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ambiguity_id'], ['ambiguity_cases.ambiguity_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    with op.batch_alter_table('clarification_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarification_questions_ambiguity_id'), ['ambiguity_id'], unique=False)

    op.create_table('contract_assumptions',
    sa.Column('assumption_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('assumption_id')
    )
    with op.batch_alter_table('contract_assumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_assumptions_contract_id'), ['contract_id'], unique=False)

    op.create_table('environment_fingerprints',
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('python_version', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_version', sa.String(), nullable=True),
    sa.Column('dependency_lock_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.evidence_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('evidence_integrities',
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_hash', sa.String(), nullable=False),
    sa.Column('hash_algorithm', sa.String(), nullable=False),
    sa.Column('input_hashes', sa.JSON(), nullable=False),
    sa.Column('parent_evidence_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.evidence_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('interpretations',
    sa.Column('interpretation_id', sa.String(length=255), nullable=False),
    sa.Column('ambiguity_id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('interpretation_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('semantic_fields', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ambiguity_id'], ['ambiguity_cases.ambiguity_id'], ),
    sa.PrimaryKeyConstraint('interpretation_id')
    )
    with op.batch_alter_table('interpretations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interpretations_ambiguity_id'), ['ambiguity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interpretations_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('invariants',
    sa.Column('invariant_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('invariant_id')
    )
    with op.batch_alter_table('invariants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invariants_contract_id'), ['contract_id'], unique=False)

    op.create_table('obligation_verification_evidence',
    sa.Column('obligation_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.evidence_id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligation_verifications.obligation_id'], ),
    sa.PrimaryKeyConstraint('obligation_id', 'evidence_id')
    )
    op.create_table('provider_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('connection_identity', sa.String(length=255), nullable=True),
    sa.Column('encrypted_credential', sa.String(length=2048), nullable=True),
    sa.Column('encryption_key_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_connections_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('provider_organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_org_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_org_id')
    )
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('repository_identifier', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('requirement_verification_evidence',
    sa.Column('verification_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.evidence_id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['requirement_verifications.id'], ),
    sa.PrimaryKeyConstraint('verification_id', 'evidence_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('verification_targets',
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('code_entity_ref', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('target_id')
    )
    with op.batch_alter_table('verification_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_targets_contract_id'), ['contract_id'], unique=False)

    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('provider_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['provider_connections.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_audit_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('provider_team_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_org_id', sa.String(length=36), nullable=False),
    sa.Column('provider_team_id', sa.String(length=255), nullable=False),
    sa.Column('sva_role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['provider_org_id'], ['provider_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repository_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('canonical_source', sa.String(length=255), nullable=False),
    sa.Column('requested_revision', sa.String(length=255), nullable=False),
    sa.Column('resolved_commit', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('manifest_hash', sa.String(length=255), nullable=False),
    sa.Column('analyzer_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_snapshots_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_snapshots_resolved_commit'), ['resolved_commit'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('analyzer_version', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_commit_id'), ['commit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('analysis_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_worker_id'), ['worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('analysis_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.alter_column('analysis_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_worker_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_analysis_id'))

    op.drop_table('analysis_jobs')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_repository_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_commit_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_snapshots_resolved_commit'))
        batch_op.drop_index(batch_op.f('ix_repository_snapshots_repository_id'))

    op.drop_table('repository_snapshots')
    op.drop_table('provider_team_mappings')
    with op.batch_alter_table('provider_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_audit_events_workspace_id'))

    op.drop_table('provider_audit_events')
    op.drop_table('workspace_memberships')
    with op.batch_alter_table('verification_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_targets_contract_id'))

    op.drop_table('verification_targets')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))

    op.drop_table('sessions')
    op.drop_table('requirement_verification_evidence')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_workspace_id'))

    op.drop_table('repositories')
    op.drop_table('provider_organizations')
    with op.batch_alter_table('provider_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_connections_workspace_id'))

    op.drop_table('provider_connections')
    op.drop_table('obligation_verification_evidence')
    with op.batch_alter_table('invariants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invariants_contract_id'))

    op.drop_table('invariants')
    with op.batch_alter_table('interpretations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interpretations_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_interpretations_ambiguity_id'))

    op.drop_table('interpretations')
    op.drop_table('evidence_integrities')
    op.drop_table('environment_fingerprints')
    with op.batch_alter_table('contract_assumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_assumptions_contract_id'))

    op.drop_table('contract_assumptions')
    with op.batch_alter_table('clarification_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarification_questions_ambiguity_id'))

    op.drop_table('clarification_questions')
    with op.batch_alter_table('behavior_expectations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavior_expectations_contract_id'))

    op.drop_table('behavior_expectations')
    op.drop_table('workspaces')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_provider_repository_id'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('verification_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_reports_repository_id'))
        batch_op.drop_index(batch_op.f('ix_verification_reports_commit_id'))

    op.drop_table('verification_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skeptic_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skeptic_reports_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_skeptic_reports_contract_id'))

    op.drop_table('skeptic_reports')
    with op.batch_alter_table('semantic_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semantic_requirements_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_semantic_requirements_analysis_id'))

    op.drop_table('semantic_requirements')
    with op.batch_alter_table('semantic_impacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semantic_impacts_change_id'))

    op.drop_table('semantic_impacts')
    with op.batch_alter_table('semantic_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semantic_contracts_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_semantic_contracts_parent_contract_id'))
        batch_op.drop_index(batch_op.f('ix_semantic_contracts_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_semantic_contracts_analysis_id'))

    op.drop_table('semantic_contracts')
    with op.batch_alter_table('semantic_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semantic_conditions_requirement_id'))

    op.drop_table('semantic_conditions')
    with op.batch_alter_table('requirement_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_verifications_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_verifications_contract_id'))

    op.drop_table('requirement_verifications')
    with op.batch_alter_table('obligation_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obligation_verifications_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_obligation_verifications_contract_id'))

    op.drop_table('obligation_verifications')
    op.drop_table('invalidation_records')
    with op.batch_alter_table('intent_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intent_candidates_analysis_id'))

    op.drop_table('intent_candidates')
    with op.batch_alter_table('execution_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_results_repository_id'))
        batch_op.drop_index(batch_op.f('ix_execution_results_commit_id'))

    op.drop_table('execution_results')
    with op.batch_alter_table('execution_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_audits_target_id'))
        batch_op.drop_index(batch_op.f('ix_execution_audits_repository_id'))
        batch_op.drop_index(batch_op.f('ix_execution_audits_obligation_id'))
        batch_op.drop_index(batch_op.f('ix_execution_audits_execution_id'))
        batch_op.drop_index(batch_op.f('ix_execution_audits_contract_id'))
        batch_op.drop_index(batch_op.f('ix_execution_audits_commit_id'))

    op.drop_table('execution_audits')
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidences_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_evidences_repository_id'))
        batch_op.drop_index(batch_op.f('ix_evidences_contract_id'))
        batch_op.drop_index(batch_op.f('ix_evidences_commit_id'))

    op.drop_table('evidences')
    with op.batch_alter_table('drift_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drift_reports_target_commit'))
        batch_op.drop_index(batch_op.f('ix_drift_reports_repository_id'))
        batch_op.drop_index(batch_op.f('ix_drift_reports_base_commit'))

    op.drop_table('drift_reports')
    with op.batch_alter_table('counterexamples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterexamples_target_id'))
        batch_op.drop_index(batch_op.f('ix_counterexamples_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_counterexamples_obligation_id'))
        batch_op.drop_index(batch_op.f('ix_counterexamples_contract_id'))

    op.drop_table('counterexamples')
    with op.batch_alter_table('change_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_records_target_commit'))
        batch_op.drop_index(batch_op.f('ix_change_records_repository_id'))
        batch_op.drop_index(batch_op.f('ix_change_records_base_commit'))

    op.drop_table('change_records')
    op.drop_table('ambiguity_cases')
    # ### end Alembic commands ###
