"""initial

Revision ID: df39e0038509
Revises: 
Create Date: 2026-09-17 00:01:38.098379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df39e0038509'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambiguity_cases',
    sa.Column('ambiguity_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('requirement_ids', sa.JSON(), nullable=False),
    sa.Column('candidate_ids', sa.JSON(), nullable=False),
    sa.Column('ambiguity_types', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('ambiguity_id')
    )
    op.create_table('change_records',
    sa.Column('change_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('base_commit', sa.String(length=255), nullable=False),
    sa.Column('target_commit', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_classification', sa.String(length=50), nullable=True),
    sa.Column('file_change_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index(op.f('ix_change_records_base_commit'), 'change_records', ['base_commit'], unique=False)
    op.create_index(op.f('ix_change_records_repository_id'), 'change_records', ['repository_id'], unique=False)
    op.create_index(op.f('ix_change_records_target_commit'), 'change_records', ['target_commit'], unique=False)
    op.create_table('counterexamples',
    sa.Column('counterexample_id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('contract_id', sa.String(length=255), nullable=True),
    sa.Column('obligation_id', sa.String(length=255), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.String(), nullable=False),
    sa.Column('preconditions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('counterexample_id')
    )
    op.create_index(op.f('ix_counterexamples_contract_id'), 'counterexamples', ['contract_id'], unique=False)
    op.create_index(op.f('ix_counterexamples_obligation_id'), 'counterexamples', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_counterexamples_requirement_id'), 'counterexamples', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_counterexamples_target_id'), 'counterexamples', ['target_id'], unique=False)
    op.create_table('drift_reports',
    sa.Column('drift_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('base_commit', sa.String(length=255), nullable=False),
    sa.Column('target_commit', sa.String(length=255), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('impacts', sa.JSON(), nullable=False),
    sa.Column('invalidations', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('drift_id')
    )
    op.create_index(op.f('ix_drift_reports_base_commit'), 'drift_reports', ['base_commit'], unique=False)
    op.create_index(op.f('ix_drift_reports_repository_id'), 'drift_reports', ['repository_id'], unique=False)
    op.create_index(op.f('ix_drift_reports_target_commit'), 'drift_reports', ['target_commit'], unique=False)
    op.create_table('evidences',
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=True),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('observation', sa.String(), nullable=False),
    sa.Column('collected_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidences_commit_id'), 'evidences', ['commit_id'], unique=False)
    op.create_index(op.f('ix_evidences_contract_id'), 'evidences', ['contract_id'], unique=False)
    op.create_index(op.f('ix_evidences_repository_id'), 'evidences', ['repository_id'], unique=False)
    op.create_index(op.f('ix_evidences_requirement_id'), 'evidences', ['requirement_id'], unique=False)
    op.create_table('execution_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('obligation_id', sa.String(length=255), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.Column('requested_permissions', sa.JSON(), nullable=False),
    sa.Column('granted_permissions', sa.JSON(), nullable=False),
    sa.Column('sandbox_backend', sa.String(length=50), nullable=False),
    sa.Column('command_identity', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_audits_commit_id'), 'execution_audits', ['commit_id'], unique=False)
    op.create_index(op.f('ix_execution_audits_contract_id'), 'execution_audits', ['contract_id'], unique=False)
    op.create_index(op.f('ix_execution_audits_execution_id'), 'execution_audits', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_audits_obligation_id'), 'execution_audits', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_execution_audits_repository_id'), 'execution_audits', ['repository_id'], unique=False)
    op.create_index(op.f('ix_execution_audits_target_id'), 'execution_audits', ['target_id'], unique=False)
    op.create_table('execution_results',
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('exit_code', sa.String(length=50), nullable=True),
    sa.Column('stdout', sa.String(), nullable=True),
    sa.Column('stderr', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.String(), nullable=True),
    sa.Column('timed_out', sa.String(length=50), nullable=True),
    sa.Column('resource_limit_exceeded', sa.String(length=50), nullable=True),
    sa.Column('sandbox_backend', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_execution_results_commit_id'), 'execution_results', ['commit_id'], unique=False)
    op.create_index(op.f('ix_execution_results_repository_id'), 'execution_results', ['repository_id'], unique=False)
    op.create_table('intent_candidates',
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('analysis_id', sa.String(length=255), nullable=False),
    sa.Column('original_statement', sa.String(), nullable=False),
    sa.Column('normalized_statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('human_confirmed', sa.Boolean(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index(op.f('ix_intent_candidates_analysis_id'), 'intent_candidates', ['analysis_id'], unique=False)
    op.create_table('invalidation_records',
    sa.Column('invalidation_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_id', sa.String(length=255), nullable=False),
    sa.Column('previous_commit', sa.String(length=255), nullable=False),
    sa.Column('target_commit', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('related_change_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('invalidation_id')
    )
    op.create_table('obligation_verifications',
    sa.Column('obligation_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=False),
    sa.Column('contradicting_evidence', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('obligation_id')
    )
    op.create_index(op.f('ix_obligation_verifications_contract_id'), 'obligation_verifications', ['contract_id'], unique=False)
    op.create_index(op.f('ix_obligation_verifications_requirement_id'), 'obligation_verifications', ['requirement_id'], unique=False)
    op.create_table('requirement_verifications',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('obligation_results', sa.JSON(), nullable=False),
    sa.Column('unresolved_obligations', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_verifications_contract_id'), 'requirement_verifications', ['contract_id'], unique=False)
    op.create_index(op.f('ix_requirement_verifications_requirement_id'), 'requirement_verifications', ['requirement_id'], unique=False)
    op.create_table('semantic_conditions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_conditions_requirement_id'), 'semantic_conditions', ['requirement_id'], unique=False)
    op.create_table('semantic_contracts',
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('contract_version', sa.String(length=50), nullable=False),
    sa.Column('parent_contract_id', sa.String(length=255), nullable=True),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('candidate_id', sa.String(length=255), nullable=True),
    sa.Column('analysis_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('compilation_status', sa.String(length=50), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index(op.f('ix_semantic_contracts_analysis_id'), 'semantic_contracts', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_semantic_contracts_candidate_id'), 'semantic_contracts', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_semantic_contracts_parent_contract_id'), 'semantic_contracts', ['parent_contract_id'], unique=False)
    op.create_index(op.f('ix_semantic_contracts_requirement_id'), 'semantic_contracts', ['requirement_id'], unique=False)
    op.create_table('semantic_impacts',
    sa.Column('impact_id', sa.String(length=255), nullable=False),
    sa.Column('change_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_id', sa.String(length=255), nullable=False),
    sa.Column('affected_requirements', sa.JSON(), nullable=False),
    sa.Column('affected_contracts', sa.JSON(), nullable=False),
    sa.Column('affected_obligations', sa.JSON(), nullable=False),
    sa.Column('affected_targets', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('impact_id')
    )
    op.create_index(op.f('ix_semantic_impacts_change_id'), 'semantic_impacts', ['change_id'], unique=False)
    op.create_table('semantic_requirements',
    sa.Column('requirement_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=True),
    sa.Column('analysis_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('original_statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_index(op.f('ix_semantic_requirements_analysis_id'), 'semantic_requirements', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_semantic_requirements_candidate_id'), 'semantic_requirements', ['candidate_id'], unique=False)
    op.create_table('skeptic_reports',
    sa.Column('report_id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('contract_id', sa.String(length=255), nullable=True),
    sa.Column('total_generated', sa.Integer(), nullable=False),
    sa.Column('total_deduplicated', sa.Integer(), nullable=False),
    sa.Column('strategies_applied', sa.JSON(), nullable=False),
    sa.Column('counterexamples', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_skeptic_reports_contract_id'), 'skeptic_reports', ['contract_id'], unique=False)
    op.create_index(op.f('ix_skeptic_reports_requirement_id'), 'skeptic_reports', ['requirement_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('verification_reports',
    sa.Column('verification_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('requirement_results', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_index(op.f('ix_verification_reports_commit_id'), 'verification_reports', ['commit_id'], unique=False)
    op.create_index(op.f('ix_verification_reports_repository_id'), 'verification_reports', ['repository_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavior_expectations',
    sa.Column('behavior_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('is_allowed', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('expected_outcome', sa.String(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('behavior_id')
    )
    op.create_index(op.f('ix_behavior_expectations_contract_id'), 'behavior_expectations', ['contract_id'], unique=False)
    op.create_table('clarification_questions',
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('ambiguity_id', sa.String(length=255), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('distinguishing_scenario_id', sa.String(length=255), nullable=True),
    sa.Column('information_gain', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ambiguity_id'], ['ambiguity_cases.ambiguity_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_clarification_questions_ambiguity_id'), 'clarification_questions', ['ambiguity_id'], unique=False)
    op.create_table('contract_assumptions',
    sa.Column('assumption_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('assumption_id')
    )
    op.create_index(op.f('ix_contract_assumptions_contract_id'), 'contract_assumptions', ['contract_id'], unique=False)
    op.create_table('environment_fingerprints',
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('os_name', sa.String(), nullable=False),
    sa.Column('python_version', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_version', sa.String(), nullable=False),
    sa.Column('dependency_lock_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.evidence_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('evidence_integrities',
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_hash', sa.String(), nullable=False),
    sa.Column('hash_algorithm', sa.String(), nullable=False),
    sa.Column('input_hashes', sa.JSON(), nullable=False),
    sa.Column('parent_evidence_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.evidence_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('interpretations',
    sa.Column('interpretation_id', sa.String(length=255), nullable=False),
    sa.Column('ambiguity_id', sa.String(length=255), nullable=False),
    sa.Column('requirement_id', sa.String(length=255), nullable=True),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('interpretation_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('semantic_fields', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ambiguity_id'], ['ambiguity_cases.ambiguity_id'], ),
    sa.PrimaryKeyConstraint('interpretation_id')
    )
    op.create_index(op.f('ix_interpretations_ambiguity_id'), 'interpretations', ['ambiguity_id'], unique=False)
    op.create_index(op.f('ix_interpretations_requirement_id'), 'interpretations', ['requirement_id'], unique=False)
    op.create_table('invariants',
    sa.Column('invariant_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('invariant_id')
    )
    op.create_index(op.f('ix_invariants_contract_id'), 'invariants', ['contract_id'], unique=False)
    op.create_table('obligation_verification_evidence',
    sa.Column('obligation_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.evidence_id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligation_verifications.obligation_id'], ),
    sa.PrimaryKeyConstraint('obligation_id', 'evidence_id')
    )
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('repository_identifier', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_workspace_id'), 'repositories', ['workspace_id'], unique=False)
    op.create_table('requirement_verification_evidence',
    sa.Column('verification_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.evidence_id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['requirement_verifications.id'], ),
    sa.PrimaryKeyConstraint('verification_id', 'evidence_id')
    )
    op.create_table('verification_targets',
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('code_entity_ref', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['semantic_contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_index(op.f('ix_verification_targets_contract_id'), 'verification_targets', ['contract_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.Column('repository_manifest_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_commit_id'), 'analyses', ['commit_id'], unique=False)
    op.create_index(op.f('ix_analyses_repository_id'), 'analyses', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_repository_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_commit_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_verification_targets_contract_id'), table_name='verification_targets')
    op.drop_table('verification_targets')
    op.drop_table('requirement_verification_evidence')
    op.drop_index(op.f('ix_repositories_workspace_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('obligation_verification_evidence')
    op.drop_index(op.f('ix_invariants_contract_id'), table_name='invariants')
    op.drop_table('invariants')
    op.drop_index(op.f('ix_interpretations_requirement_id'), table_name='interpretations')
    op.drop_index(op.f('ix_interpretations_ambiguity_id'), table_name='interpretations')
    op.drop_table('interpretations')
    op.drop_table('evidence_integrities')
    op.drop_table('environment_fingerprints')
    op.drop_index(op.f('ix_contract_assumptions_contract_id'), table_name='contract_assumptions')
    op.drop_table('contract_assumptions')
    op.drop_index(op.f('ix_clarification_questions_ambiguity_id'), table_name='clarification_questions')
    op.drop_table('clarification_questions')
    op.drop_index(op.f('ix_behavior_expectations_contract_id'), table_name='behavior_expectations')
    op.drop_table('behavior_expectations')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_verification_reports_repository_id'), table_name='verification_reports')
    op.drop_index(op.f('ix_verification_reports_commit_id'), table_name='verification_reports')
    op.drop_table('verification_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skeptic_reports_requirement_id'), table_name='skeptic_reports')
    op.drop_index(op.f('ix_skeptic_reports_contract_id'), table_name='skeptic_reports')
    op.drop_table('skeptic_reports')
    op.drop_index(op.f('ix_semantic_requirements_candidate_id'), table_name='semantic_requirements')
    op.drop_index(op.f('ix_semantic_requirements_analysis_id'), table_name='semantic_requirements')
    op.drop_table('semantic_requirements')
    op.drop_index(op.f('ix_semantic_impacts_change_id'), table_name='semantic_impacts')
    op.drop_table('semantic_impacts')
    op.drop_index(op.f('ix_semantic_contracts_requirement_id'), table_name='semantic_contracts')
    op.drop_index(op.f('ix_semantic_contracts_parent_contract_id'), table_name='semantic_contracts')
    op.drop_index(op.f('ix_semantic_contracts_candidate_id'), table_name='semantic_contracts')
    op.drop_index(op.f('ix_semantic_contracts_analysis_id'), table_name='semantic_contracts')
    op.drop_table('semantic_contracts')
    op.drop_index(op.f('ix_semantic_conditions_requirement_id'), table_name='semantic_conditions')
    op.drop_table('semantic_conditions')
    op.drop_index(op.f('ix_requirement_verifications_requirement_id'), table_name='requirement_verifications')
    op.drop_index(op.f('ix_requirement_verifications_contract_id'), table_name='requirement_verifications')
    op.drop_table('requirement_verifications')
    op.drop_index(op.f('ix_obligation_verifications_requirement_id'), table_name='obligation_verifications')
    op.drop_index(op.f('ix_obligation_verifications_contract_id'), table_name='obligation_verifications')
    op.drop_table('obligation_verifications')
    op.drop_table('invalidation_records')
    op.drop_index(op.f('ix_intent_candidates_analysis_id'), table_name='intent_candidates')
    op.drop_table('intent_candidates')
    op.drop_index(op.f('ix_execution_results_repository_id'), table_name='execution_results')
    op.drop_index(op.f('ix_execution_results_commit_id'), table_name='execution_results')
    op.drop_table('execution_results')
    op.drop_index(op.f('ix_execution_audits_target_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_repository_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_obligation_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_execution_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_contract_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_commit_id'), table_name='execution_audits')
    op.drop_table('execution_audits')
    op.drop_index(op.f('ix_evidences_requirement_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_repository_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_contract_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_commit_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_drift_reports_target_commit'), table_name='drift_reports')
    op.drop_index(op.f('ix_drift_reports_repository_id'), table_name='drift_reports')
    op.drop_index(op.f('ix_drift_reports_base_commit'), table_name='drift_reports')
    op.drop_table('drift_reports')
    op.drop_index(op.f('ix_counterexamples_target_id'), table_name='counterexamples')
    op.drop_index(op.f('ix_counterexamples_requirement_id'), table_name='counterexamples')
    op.drop_index(op.f('ix_counterexamples_obligation_id'), table_name='counterexamples')
    op.drop_index(op.f('ix_counterexamples_contract_id'), table_name='counterexamples')
    op.drop_table('counterexamples')
    op.drop_index(op.f('ix_change_records_target_commit'), table_name='change_records')
    op.drop_index(op.f('ix_change_records_repository_id'), table_name='change_records')
    op.drop_index(op.f('ix_change_records_base_commit'), table_name='change_records')
    op.drop_table('change_records')
    op.drop_table('ambiguity_cases')
    # ### end Alembic commands ###
