"""add_executions_table

Revision ID: f5a124d6c534
Revises: ba9ffc60b46c
Create Date: 2026-09-17 15:01:54.400686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a124d6c534'
down_revision: Union[str, Sequence[str], None] = 'ba9ffc60b46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('commit_id', sa.String(length=40), nullable=False),
    sa.Column('verification_target_id', sa.String(length=36), nullable=False),
    sa.Column('obligation_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=False),
    sa.Column('sandbox_backend', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=64), nullable=False),
    sa.Column('end_time', sa.String(length=64), nullable=False),
    sa.Column('stdout_hash', sa.String(length=64), nullable=True),
    sa.Column('stderr_hash', sa.String(length=64), nullable=True),
    sa.Column('resource_observations', sa.Text(), nullable=True),
    sa.Column('environment_fingerprint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executions_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_job_id'), ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_job_id'))
        batch_op.drop_index(batch_op.f('ix_executions_analysis_id'))
    op.drop_table('executions')
    # ### end Alembic commands ###
