"""
Tests for FileClassifier
=========================

Verifies the 10-tier priority classification system.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from app.repository.classifier.file_classifier import FileClassifier
from app.repository.types import FileClassification


@pytest.fixture
def classifier() -> FileClassifier:
    return FileClassifier()


class TestAssetClassification:
    def test_image_is_asset(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("logo.png")).category == FileClassification.ASSET
        assert classifier.classify(Path("icon.ico")).category == FileClassification.ASSET

    def test_font_is_asset(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("fonts/Inter.woff2")).category == FileClassification.ASSET

    def test_binary_data_is_asset(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("data.bin")).category == FileClassification.ASSET
        assert classifier.classify(Path("archive.zip")).category == FileClassification.ASSET


class TestVendorClassification:
    def test_vendor_directory(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("vendor/some_lib/file.py")).category == FileClassification.VENDOR

    def test_node_modules(self, classifier: FileClassifier) -> None:
        pass

    def test_third_party_directory(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("third_party/lib/main.c")).category == FileClassification.VENDOR


class TestGeneratedClassification:
    def test_minified_js(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("app.min.js")).category == FileClassification.GENERATED

    def test_bundle_css(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("styles.bundle.css")).category == FileClassification.GENERATED

    def test_protobuf_go(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("user.pb.go")).category == FileClassification.GENERATED

    def test_generated_content_signature(self, classifier: FileClassifier) -> None:
        first_bytes = b"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage user"
        assert classifier.classify(Path("user.go"), first_bytes=first_bytes).category == FileClassification.GENERATED


class TestTestClassification:
    def test_test_directory(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("tests/utils.py")).category == FileClassification.TEST
        assert classifier.classify(Path("src/__tests__/Component.tsx")).category == FileClassification.TEST

    def test_test_filename_prefix(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("test_utils.py")).category == FileClassification.TEST

    def test_test_filename_suffix(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("utils_test.py")).category == FileClassification.TEST
        assert classifier.classify(Path("Component.test.tsx")).category == FileClassification.TEST
        assert classifier.classify(Path("Service.spec.ts")).category == FileClassification.TEST


class TestDocumentationClassification:
    def test_readme(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("README.md")).category == FileClassification.DOCUMENTATION
        assert classifier.classify(Path("readme")).category == FileClassification.DOCUMENTATION

    def test_license(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("LICENSE")).category == FileClassification.DOCUMENTATION

    def test_docs_directory(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("docs/architecture.md")).category == FileClassification.DOCUMENTATION
        # Should not classify non-doc extensions in docs dir as documentation (e.g. scripts)
        assert classifier.classify(Path("docs/generate.py"), language="Python").category != FileClassification.DOCUMENTATION


class TestInfrastructureClassification:
    def test_dockerfile(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("Dockerfile")).category == FileClassification.INFRASTRUCTURE

    def test_docker_compose(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("docker-compose.yml")).category == FileClassification.INFRASTRUCTURE

    def test_github_actions(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path(".github/workflows/ci.yml")).category == FileClassification.CI_CD

    def test_terraform(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("main.tf")).category == FileClassification.INFRASTRUCTURE


class TestApiSchemaClassification:
    def test_graphql(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("schema.graphql")).category == FileClassification.API_SCHEMA

    def test_openapi(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("openapi.yaml")).category == FileClassification.API_SCHEMA

    def test_api_dir(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("api/routes.json")).category == FileClassification.API_SCHEMA


class TestDatabaseClassification:
    def test_sql(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("init.sql")).category == FileClassification.DATABASE_SCHEMA

    def test_migrations_dir(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("migrations/001_init.py")).category == FileClassification.DATABASE_SCHEMA


class TestConfigurationClassification:
    def test_package_json(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("package.json")).category == FileClassification.CONFIGURATION

    def test_pyproject_toml(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("pyproject.toml")).category == FileClassification.CONFIGURATION

    def test_generic_config_extension(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("custom.ini")).category == FileClassification.CONFIGURATION


class TestSourceCodeClassification:
    def test_python_source(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("main.py"), language="Python").category == FileClassification.SOURCE_CODE

    def test_js_source(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("src/app.js"), language="JavaScript").category == FileClassification.SOURCE_CODE

    def test_unknown_language_not_source(self, classifier: FileClassifier) -> None:
        assert classifier.classify(Path("mystery.file"), language=None).category == FileClassification.UNKNOWN
